### ISSUE TITLE
Cannot add new images

### ISSUE THREAD

**Issue by satyamele** [VPanjeta/Deep-Object-Removal#1]
I tried adding new Images to the project with the dimension 400x400 but unable to change it 
**Traceback (most recent call last):
  File "main.py", line 76, in <module>
    sub_window = np.hstack((image, blank, filtered_image[:,:,[2, 1, 0]]))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py", line 293, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly**

Getting this error!

**Comment by VPanjeta** [comment]
This a numpy error generally thrown when the dimensions of your custom data do not match the data expected in the code.  
Ensure that your image is of the same size, type and format as the example images present.
Just to make sure that it is not an error with the code you can try to replicate the images present in the folder by creating copies of the given images and see if it works then.
