### ISSUE TITLE
Possible paid collaboration for a project?

### ISSUE THREAD

**Issue by SocialKitLtd** [VPanjeta/Deep-Object-Removal#3]
Hey there,

I couldn't find an email so I'm writing here.
Would you be interested in a paid collaboration with my company? We are looking to develop an app that removes objects from images (similar to this: https://apps.apple.com/us/app/touchretouch/id373311252) using inpaint technique. We will take care of the entire app development, including the actual component for the masking, etc'. The user will use his fingers to choose the "removed object". But we need help to develop to object inpaint removal algorithm under the hood.  
Is it something you'll find interesting?

Roi

**Comment by VPanjeta** [comment]
Hi.

Since this is not really an issue I will be closing this thread. In case you want to discuss this further, you can write a mail to me with all technical requirement of the project (like size, memory requirement, on-cloud or on-device architecture, etc).
My email id is vishalpanjeta@gmail.com
