### ISSUE TITLE
How to save the masked Image to local

### ISSUE THREAD

**Issue by Hiteshsaai** [VPanjeta/Deep-Object-Removal#5]
I am using the object removal model and it is working fine, but I don't know how to save the masked image, is there a way to do that?

**Comment by VPanjeta** [comment]
Hi @Hiteshsaai 

Sorry for a not so well documented project. Anyway, you can try to save the masked image from [Line no 92](https://github.com/VPanjeta/Deep-Object-Removal/blob/bc8b7da8b09fc7fc1fd51181e331ce0523abc5a1/main.py#L92). The variable `input_image_masked` is an array which you can use to save the image directly to disk using `imwrite` function of cv2 ibrary which is already imported.

**Comment by Hiteshsaai** [comment]
you are talking about the resultant/output image, right?

**Comment by VPanjeta** [comment]
No I was talking about the masked image. Anyway, a better way would be to create 2 folders `results` and `inputs` in the same folder from where you're executing this and uncomment line number 103 and 104 in `main.py`  
That should save the masked inputs and the results of the model in those folders.

**Comment by Hiteshsaai** [comment]
I solved the issue, by uncommenting the line of code, thanks for the help @VPanjeta .

**Comment by VPanjeta** [comment]
OK cool. Closing this.
